MaterializeInc/rust-dec

dec/CHANGELOG.md, dec/src/decimal128.rs, dec/src/decimal32.rs, dec/src/decimal64.rs, dec/src/ordered.rs, dec/tests/dec.rs
@benesch I looked into implementing `Context<OrderedDecimal<D>>`, as well, but figured this was a reasonable place to start.
=> dec: add boilerplate impls to OrderedDecimal<D>

dec/CHANGELOG.md, dec/src/conv.rs, dec/src/decimal128.rs, dec/src/decimal64.rs, dec/src/lib.rs, dec/src/tests.rs, dec/tests/dec.rs
Converting from 64- and 128-bit ints to `Decimal128` greatly simplifies code within Materialize, and provides library-level support for users who might want to accomplish the same thing.
@benesch I tried making `from_int_gt_32_bits` into a function using generics in lieu of the `$ty` parameters on the macro, but getting it to work required implementing some traits that were more code than felt worthwhile. lmk if this approach suffices, or if you either understand a way to implement this without traits, or if you'd prefer a trait-ed function.
=> dec: support cast from i/u64 to Decimal64/128 + i/u128 to Decimal128

dec/src/ordered.rs, dec/tests/dec.rs
Decimal<N>'s internal BCD vec is only valid for its number of
digits/3. Previously, we calculated OrderedDecimal<Decimal<N>>
values' hashes using the entire BCD vec (i.e. not only the valid
elements), which generated an inconsistent hash for equivalent
representations of the same value.
=> dec: fix Hash for OrderedDecimal<Decimal<N>>

dec/src/decimal.rs
This simplifies taking in values from Avro that will get sent to MZ as coefficient and scale.
=> dec: add set_exponent to Decimal<N>

dec/benches/dec.rs, dec/src/decimal.rs, dec/src/error.rs, dec/tests/dec.rs
This implementation differs slightly from the approach taken in the underlying C library in that we use `checked_add` or `checked_sub` to natively handle accumulating values into their primitive type, whereas the C library does some hokey-pokey by accumulating the value mod 10 and tracking the least significant digit separately. I implemented a pretty faithful transliteration of the C approach, but it performed ~10% worse than the approach in this PR.
@benesch Given that the volume of tests is becoming unwieldy, would you suggest breaking the tests down into a file for each type? Or do you think this isn't at the breaking point yet?
=> Support converting Decimal<N> to primitive int

dec/CHANGELOG.md, dec/src/conv.rs, dec/tests/dec.rs, dec/tests/serde.rs
`to_standard_notation_string`'s macro didn't support special values, but it should!
=> dec: support to_standard_notation_string for non-finite values

dec/CHANGELOG.md, dec/src/decimal.rs, dectest/src/backend/decimal.rs
Need this to support casting `rust-dec` values in Materialize to ints.
=> dec: support round for Decimal

dec/src/decimal.rs, dec/src/decimal128.rs, dec/src/decimal32.rs, dec/src/decimal64.rs, dec/tests/serde.rs
`decNumber` only fills a decimal's LSU with as many digits as necessary, leaving the remainder of the buffer filled with uninitialized junk. This PR provides a method to set those remaining values to `0`.
This is necessary because Materialize uses row's byte representation to asses equality; these junk values make it impossible to implement e.g. `DISTINCT`.
This issue also crept up previously in testing our `serde` implementation, and this method provides a simple mechanism by which we can reinstate the test.
=> LSU cleanup

dec/src/decimal64.rs
This was fine when compiling the library, but Materialize disliked the previous expression, so making it consistent with `Decimal128::coefficient_digits`.
=> dec: fix FFI call in Decimal64::coefficient_digits

dec/CHANGELOG.md, dec/src/decimal.rs, dec/tests/dec.rs
Note that this does, in fact, fix the issue we were seeing using byte equality in Materialize; tysm for figuring that out, @benesch
=> dec: support creating Decimal from raw parts

dec/CHANGELOG.md, dec/src/decimal.rs
This was private largely because I didn't see a use for it to be publicly visible, but I discovered one (speeding up the encoding process for values sent over PG wire), so moving it to public.
=> dec: make Decimal::coefficient_units public

dec/src/decimal.rs
The only [bug](https://materializeinc.slack.com/archives/CMH6PG4CW/p1624575648320000) I found during dogfood day!
=> fix compilation error for target_pointer_width=32

dec/benches/dec.rs, dec/src/conv.rs, dec/src/decimal.rs, dec/src/decimal128.rs, dec/src/decimal64.rs, dec/tests/dec.rs
Implements a more faithful transliteration of the `libdecnumber` printing functions (e.g. [`decimal64ToString`](https://github.com/MaterializeInc/rust-dec/blob/master/decnumber-sys/decnumber/decimal64.c#L285)) adapted for standard notation.
@benesch Only a performance improvement,  but now has benchmark parity with the underlying C library so think it's a nice win.
cc @elindsey just because you expressed some interest in seeing the problem
=> dec: refactor to_standard_notation_string

dec/src/decimal128.rs, dec/src/decimal32.rs, dec/src/decimal64.rs
=> dec: mark static-sized Decimal types as repr(transparent)

dec/CHANGELOG.md, dec/src/decimal.rs, dec/tests/dec.rs
The prior implementation of the raw_parts functions potentially
mangled endianness if ported across machines with different endianness.
This commit refactors this to make managing the LSU's conversion
to bytes an issue for the client.
This essentially undoes the majority of #42, which I had implemented
so as to provide an immediate LSU-to-byte transformation in the library,
rather than implementing the transformation in my application. That is
to say that #42 was over-eager and should not have been committed.
Addresses some comments from MaterializeInc/materialize#9406
=> dec: refactor *_raw_parts to represent LSU values with u16s

dec/CHANGELOG.md, dec/src/decimal.rs, dec/tests/dec.rs
This makes `from_raw_parts` cheaper because the `lsu` length does not
need validation.
=> dec: use [u16; N] as lsu type in {to,from}_raw_parts

dec/src/ordered.rs
Same reasoning as https://github.com/MaterializeInc/rust-dec/issues/54, but this time applied to `OrderedDecimal`.
=> Make OrderedDecimal #[repr(transparent)]

.github/workflows/ci.yml, dec/CHANGELOG.md, dec/Cargo.toml, dec/src/decimal.rs, dec/src/decimal128.rs, dec/src/decimal64.rs
Adds an optional dependency on the [`num-traits`](https://github.com/rust-num/num-traits) crate, and implements some of that crate's traits for `Decimal64`, `Decimal128`, and `Decimal<N>`.
=> Implement traits from `num-traits` for Decimal types

dec/src/decimal.rs, dec/src/decimal128.rs, dec/src/decimal64.rs
When calling a decnumber_sys function where one of the inputs is used as the output, we need to be careful to pass the *same* pointer in for both inputs, rather than constructing two different pointers, or we run afoul of the stacked borrow check in Miri.
Fix #74.
Close #75.
=> fix stacked borrow violations

dec/src/decimal.rs, dec/src/decimal128.rs, dec/src/decimal32.rs, dec/src/decimal64.rs, decnumber-sys/src/lib.rs, decnumber-sys/tests/basic.rs
Several fixes to bugs that are documented in #76. All tests pass in Miri with this commit except for `test_overloading`.
=> Fixes for `MaybeUninit<T>::assume_init()` and uninitialized reads documented in #76

decnumber-sys/decnumber/decBasic.c, decnumber-sys/decnumber/decCommon.c, decnumber-sys/decnumber/decNumber.c
Based on the suggestions from Jakub Jelinek in https://gcc.gnu.org/pipermail/gcc-patches/2024-February/644843.html and https://gcc.gnu.org/pipermail/gcc-patches/2024-February/644844.html and the patch by @icmccorm  in https://gcc.gnu.org/pipermail/gcc-patches/2024-February/644840.html
Fixes: https://github.com/MaterializeInc/materialize/issues/25634
Fixes: https://github.com/MaterializeInc/rust-dec/issues/80
=> Fix undefined behavior in libdecnumber

dec/benches/dec.rs, dec/src/decimal.rs, systest/Cargo.toml
This PR improves the routines that convert `f64` values into `Decimal<N>` values by avoiding allocating large strings. The performance comes from:
* Serializing the float using the scientific notation, which uses at most 24 characters as opposed to ~800 characters of the only decimal notation.
* Avoiding all roundtrips to the allocator by writing into a small stack allocated buffer
I have included a benchmark for the `from_f64` method which shows a 4x improvement:
```
parse_decimal           time:   [658.76 ns 661.73 ns 665.05 ns]                           
change: [-78.751% -78.645% -78.534%] (p = 0.00 < 0.05)
Performance has improved.
```
=> add parsing variant that doesn't allocate

dec/src/decimal.rs
This PR fixes a regression introduced in #83 which started serializing floats using their scientific notation, which is much shorter than the decimal notation and therefore faster.
It turns out that conversion from string to decimal is syntactic instead of semantic. This means that the strings "12" and "1.2E2", which are semantically the same number, parse into a different Decimal instance.
This PR fixes the regression by serializing to the decimal representation.
The overall improvement from 0.4.9 is much more mild as a result.
```
parse_decimal           time:   [2.4036 µs 2.4180 µs 2.4389 µs]
change: [-22.670% -21.979% -21.336%] (p = 0.00 < 0.05)
Performance has improved.
```
=> dec: use decimal representation when converting to Decimal
